RHMAP-11600 - testing jenkins build job
feedhenry/fh-dataman pull request #1
Opened 2016-12-12 15:26 UTC by rachael-oregan

2016-12-12 15:54 UTC, grdryn commented
Retest this please.

2016-12-12 15:56 UTC, grdryn commented
Retest this please.

2016-12-12 15:58 UTC, grdryn commented
Retest this please.

2016-12-12 15:59 UTC, grdryn commented
Retest this please.

2016-12-12 16:01 UTC, grdryn commented
Retest this please.

2016-12-13 11:11 UTC, fh-qube commented
SonarQube analysis reported 3 issues:
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 3 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Remove this logging statement.](https://github.com/feedhenry/fh-dataman/blob/fa2f4d2d7be3e01efa14012dbb5a420ddce39c0e/src/app.js#L127) [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AS2228)
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Remove this logging statement.](https://github.com/feedhenry/fh-dataman/blob/fa2f4d2d7be3e01efa14012dbb5a420ddce39c0e/src/app.js#L142) [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AS2228)
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Remove this logging statement.](https://github.com/feedhenry/fh-dataman/blob/fa2f4d2d7be3e01efa14012dbb5a420ddce39c0e/src/app.js#L31) [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AS2228)

2016-12-13 11:12 UTC, fh-qube commented
SonarQube analysis reported 3 issues:
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 3 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Remove this logging statement.](https://github.com/feedhenry/fh-dataman/blob/6f9ba55fa8f3d60070f87bd4773e5b95f0171386/src/app.js#L127) [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AS2228)
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Remove this logging statement.](https://github.com/feedhenry/fh-dataman/blob/6f9ba55fa8f3d60070f87bd4773e5b95f0171386/src/app.js#L31) [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AS2228)
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Remove this logging statement.](https://github.com/feedhenry/fh-dataman/blob/6f9ba55fa8f3d60070f87bd4773e5b95f0171386/src/app.js#L142) [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AS2228)

2016-12-13 11:20 UTC, fh-qube commented
SonarQube analysis reported 3 issues:
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 3 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Remove this logging statement.](https://github.com/feedhenry/fh-dataman/blob/3d5f12d000a3ee605cfba1418208df35600f6a26/src/app.js#L142) [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AS2228)
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Remove this logging statement.](https://github.com/feedhenry/fh-dataman/blob/3d5f12d000a3ee605cfba1418208df35600f6a26/src/app.js#L127) [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AS2228)
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Remove this logging statement.](https://github.com/feedhenry/fh-dataman/blob/3d5f12d000a3ee605cfba1418208df35600f6a26/src/app.js#L31) [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AS2228)

2016-12-13 12:16 UTC, fh-qube commented
SonarQube analysis reported 3 issues:
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 3 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Remove this logging statement.](https://github.com/feedhenry/fh-dataman/blob/a6d32ebcfa4f007d079ded53d959c4d62519d6f1/src/app.js#L31) [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AS2228)
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Remove this logging statement.](https://github.com/feedhenry/fh-dataman/blob/a6d32ebcfa4f007d079ded53d959c4d62519d6f1/src/app.js#L142) [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AS2228)
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Remove this logging statement.](https://github.com/feedhenry/fh-dataman/blob/a6d32ebcfa4f007d079ded53d959c4d62519d6f1/src/app.js#L127) [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AS2228)

2016-12-13 12:17 UTC, fh-qube commented
SonarQube analysis reported 3 issues:
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 3 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Remove this logging statement.](https://github.com/feedhenry/fh-dataman/blob/11aee9aa5495ac32b6057916c827508fd9bac230/src/app.js#L142) [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AS2228)
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Remove this logging statement.](https://github.com/feedhenry/fh-dataman/blob/11aee9aa5495ac32b6057916c827508fd9bac230/src/app.js#L31) [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AS2228)
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Remove this logging statement.](https://github.com/feedhenry/fh-dataman/blob/11aee9aa5495ac32b6057916c827508fd9bac230/src/app.js#L127) [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AS2228)

2016-12-13 12:50 UTC, fh-qube commented
SonarQube analysis reported 3 issues:
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 3 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Remove this logging statement.](https://github.com/feedhenry/fh-dataman/blob/2a8490bcba4cd46c2f16cd181a7093ec7135ac57/src/app.js#L126) [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AS2228)
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Remove this logging statement.](https://github.com/feedhenry/fh-dataman/blob/2a8490bcba4cd46c2f16cd181a7093ec7135ac57/src/app.js#L141) [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AS2228)
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) [Remove this logging statement.](https://github.com/feedhenry/fh-dataman/blob/2a8490bcba4cd46c2f16cd181a7093ec7135ac57/src/app.js#L30) [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://metrics.skunkhenry.com/coding_rules#rule_key=javascript%3AS2228)

2016-12-13 13:00 UTC, pb82 requested changes

2016-12-13 13:00 UTC, pb82 commented on test/dummy_test.js
> +export function dummy_test(done) {
Can we add `mocha` to the dependencies and use this for the tests? All new components and tests should be written using mocha.

2016-12-13 13:02 UTC, rachael-oregan commented on test/dummy_test.js
> +export function dummy_test(done) {
Ok I'll add `mocha` in now

2016-12-13 13:23 UTC, rachael-oregan commented
Retest this please

2016-12-13 13:29 UTC, rachael-oregan commented
Retest this please

2016-12-14 14:56 UTC, wei-lee approved these changes
LGTM

2016-12-14 14:56 UTC, wei-lee commented on package.json
> +    "sinon": "^1.17.6"
I think sinon should be devDependencies?

2016-12-14 14:56 UTC, wei-lee commented on test/dummy_test.js
> +export function dummy_test(done) {
it's already added

2016-12-14 15:21 UTC, merged