RHMAP-11589 - create delete api to delete collections
feedhenry/fh-dataman pull request #10
Opened 2017-01-13 18:23 UTC by rachael-oregan

# Motivation
Create an API to delete selected collection(s)

# Result
A delete endpoint that takes an array of collection names as parameters, checks if the collections requested for deletion exist in the database and then deletes them.

# Jira
https://issues.jboss.org/browse/RHMAP-11589

2017-01-13 18:51 UTC, wei-lee requested changes
we should also add an integration test for the delete action

2017-01-13 18:51 UTC, wei-lee commented on src/endpoints/http/collections/delete.js
> +    const allCollectionNames = req.db.getCollectionNames();
I would consider the code from here is the business logic. I would prefer us to move the business logic out of the controller, even if sometimes the business logic is relatively simple. I think there are a few benefits:

1. loose coupling between controllers and the business logic. Make it easier to move the business logic if we need to.
2. easier to test the business logic.
3. keep things consistent. Make it looks like the code is written by one developer.

See https://github.com/feedhenry/fh-dataman/blob/master/src/endpoints/http/collections/index.js#L4 for example.

2017-01-13 18:51 UTC, wei-lee commented on src/endpoints/http/collections/delete.js
> +    _.filter(reqCollections, function(name) {
I think we should first check all the collection names are actually valid. If there is any collection name do not exist, return the error.

2017-01-13 18:51 UTC, wei-lee commented on src/endpoints/http/collections/delete.js
> +        req.db.collectionToDelete.drop();
perhaps consider using Promise.all or async.series here to wait for the collection drop action to complete. At the moment, the user will not know even if the collection failed to drop

2017-01-13 18:51 UTC, wei-lee commented on src/endpoints/http/collections/delete_test.js
> +import bodyParser from 'body-parser';
if we separate out the business logic (delete collections) out of the controller, this test can be easily written without the need of supertest

2017-01-16 09:56 UTC, rachael-oregan commented on src/endpoints/http/collections/delete.js
> +    _.filter(reqCollections, function(name) {
The way I'm checking if the collection names are valid is through the `includes()` function. The `filter()` function iterates over the array `reqCollections` and if an element exists in the `allCollectionNames` array then I get the collection by `req.db.getCollection(name)`. I'll add in that an error is returned if it doesn't exist

2017-01-16 10:03 UTC, rachael-oregan commented on src/endpoints/http/collections/delete.js
> +    const allCollectionNames = req.db.getCollectionNames();
That's grand I'll move the business logic. Just wondering, why is the business logic in the create controller?

2017-01-16 11:51 UTC, wei-lee commented on src/endpoints/http/collections/delete.js
> +    const allCollectionNames = req.db.getCollectionNames();
@rachael-oregan  which create controller?

2017-01-16 12:02 UTC, rachael-oregan commented on src/endpoints/http/collections/delete.js
> +    const allCollectionNames = req.db.getCollectionNames();
@wei-lee https://github.com/feedhenry/fh-dataman/blob/master/src/endpoints/http/collections/create.js#L11

2017-01-16 12:03 UTC, wei-lee commented on src/endpoints/http/collections/delete.js
> +    const allCollectionNames = req.db.getCollectionNames();
@rachael-oregan right. Yeah, we might need to refactor the creation to keep things consistent.

2017-01-23 15:55 UTC, closed without merging