integration test for collection upload
feedhenry/fh-dataman pull request #22
Opened 2017-02-16 17:11 UTC by thailekha

Motivation:
Integration test for https://issues.jboss.org/browse/RHMAP-11591

JIRA: https://issues.jboss.org/browse/RHMAP-13466

2017-02-17 15:42 UTC, sedroche requested changes
Couple of comments

2017-02-17 15:42 UTC, sedroche commented on src/endpoints/http/collections/index.js
> +
can you remove this whitespace here and the other places?

2017-02-17 15:42 UTC, sedroche commented on test/integration/test_collections.js
> +    'test_collection_upload': function(done) {
I like the test but you can remove the `ext` parameter by doing:
```javascript
    'test_collection_upload': function(done) {
      const test = exts => {
        if (!exts.length) {
          return done();
        }

        const ext = exts.shift();
        chai.request(SERVER_URL)
          .post(`${PATH_PREFIX}/collections/upload`)
          .attach('file', fs.readFileSync(`${__dirname}/fixture/import.${ext}`), `import.${ext}` )
          .set('Authorization', `Bearer ${TOKEN}`)
          .end((err, res) => {
            expect(err).to.be.null;
            expect(res).to.have.status(201);

            mongodbClient.dropCollection('import', test.bind(null, exts));
          });
      };

      test(['json','csv','bson']);
    }
```

Also can you fix the indentation on the function chain? 2 spaces like in my example above.

2017-02-17 15:42 UTC, sedroche commented on test/integration/test_collections.js
> +      test(extensions.shift(), extensions);
I just want to make sure we are ok with using the recursive method here. It's slightly different to how other tests are written.

The other option is using async and would look something like
```javascript
    'test_collection_upload': function(done) {
      const test = (ext, cb) => {
        chai.request(SERVER_URL)
          .post(`${PATH_PREFIX}/collections/upload`)
          .attach('file', fs.readFileSync(`${__dirname}/fixture/import.${ext}`), `import.${ext}` )
          .set('Authorization', `Bearer ${TOKEN}`)
          .end((err, res) => {
            expect(err).to.be.null;
            expect(res).to.have.status(201);
            mongodbClient.dropCollection('import', cb);
          });
      };

      async.eachSeries(['json','csv','bson'], function(ext, cb) {
        test(ext, cb);
      }, done);
    }
```

Thoughts @pb82 @rachael-oregan ?

2017-02-23 12:04 UTC, sedroche commented on api-docs/swagger.yaml
> +        Upload json, bson, or csv file to import collection(s)
Change this to "Upload json, bson, or csv file collection(s)"

2017-02-23 12:07 UTC, sedroche commented on api-docs/swagger.yaml
> +      operationId: uploadCollection
I misunderstood this when you asked. Can you change this to `insertCollection` please?

2017-02-23 12:30 UTC, sedroche commented on test/integration/test_collections.js
> +      test(['json','csv','bson']);
I just want to make sure we are ok with using the recursive method here. It's slightly different to how other tests are written and we might want to maintain consistent code.

The other option is using async and would look something like
```javascript
    'test_collection_upload': function(done) {
      const test = (ext, cb) => {
        chai.request(SERVER_URL)
          .post(`${PATH_PREFIX}/collections/upload`)
          .attach('file', fs.readFileSync(`${__dirname}/fixture/import.${ext}`), `import.${ext}` )
          .set('Authorization', `Bearer ${TOKEN}`)
          .end((err, res) => {
            expect(err).to.be.null;
            expect(res).to.have.status(201);
            mongodbClient.dropCollection('import', cb);
          });
      };

      async.eachSeries(['json','csv','bson'],  test, done);
    }
```

Thoughts @pb82 @rachael-oregan ?

2017-02-23 12:56 UTC, rachael-oregan commented on test/integration/test_collections.js
> +      test(['json','csv','bson']);
I think we should try keep the code consistent, it's more readable

2017-02-23 13:00 UTC, pb82 commented on test/integration/test_collections.js
> +      test(['json','csv','bson']);
I also think that using `async` is a bit nicer. But not a big deal.

2017-02-23 13:03 UTC, pb82 approved these changes
LGTM, just a comment

2017-02-23 17:49 UTC, merged